spring:
  application:
    name: Stage-spring-angular


  h2:
    datasource:
      url: jdbc:h2:mem:students_db
    console:
      enabled: true


  datasource:
    mysql:
      url: jdbc:mysql://localhost:3307/stage_db?useSSL=false&serverTimezone=UTC
      username: root
      password: root
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mvc:
    format:
      date: d/M/yyyy


  mail:
    host: smtp.gmail.com
    port: 587
    username: mohamedkhlifi97@gmail.com
    password: udxlplahjzjabnrx



    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  security:
    oauth2:
      resourceserver:
          jwt:
            issuer-uri: http://localhost:8080/realms/TestRealm
            jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: stage_client
            authorization-grant-type: password

server:
  port: 8021


keycloak:
  server-url: http://localhost:8080
  realm: TestRealm
  client-id: stage_client
  clientSecret: M9smGwF5aS8nxAz0NjJ1zJBG8B6Fuy6y
  username: mohamedkhlifi
  password: 1212

